In [15]:
import pandas as pd
import numpy as np

df=pd.read_excel("Telco_customer_churn.xlsx")
df.tail(20)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
7023,4807-IZYOZ,1,United States,California,North Palm Springs,92258,"33.906496, -116.569499",33.906496,-116.569499,Female,No,No,No,51,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),20.65,1020.75,No,0,70,4725,NaN
7024,9710-NJERN,1,United States,California,Palm Desert,92260,"33.694501, -116.412711",33.694501,-116.412711,Female,No,No,No,39,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.15,826,No,0,44,2007,NaN
7025,9837-FWLCH,1,United States,California,Palm Springs,92262,"33.839989, -116.659215",33.839989,-116.659215,Male,No,Yes,Yes,12,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Electronic check,19.20,239,No,0,73,3101,NaN
7026,7203-OYKCT,1,United States,California,Palo Verde,92266,"33.3249, -114.758334",33.324900,-114.758334,Male,No,No,No,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Electronic check,104.95,7544.3,No,0,20,5760,NaN
7027,1035-IPQPU,1,United States,California,Parker Dam,92267,"34.273872, -114.192901",34.273872,-114.192901,Female,Yes,Yes,No,63,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,103.50,6479.4,No,0,53,5187,NaN
7028,7398-LXGYX,1,United States,California,Pioneertown,92268,"34.201108, -116.593456",34.201108,-116.593456,Male,No,Yes,No,44,Yes,Yes,Fiber optic,Yes,No,Yes,No,No,No,Month-to-month,Yes,Credit card (automatic),84.80,3626.35,No,0,44,2770,NaN
7029,2823-LKABH,1,United States,California,Rancho Mirage,92270,"33.763678, -116.429928",33.763678,-116.429928,Female,No,No,No,18,Yes,Yes,Fiber optic,No,No,Yes,Yes,No,Yes,Month-to-month,Yes,Bank transfer (automatic),95.05,1679.4,No,0,60,4524,NaN
7030,0550-DCXLH,1,United States,California,Thermal,92274,"33.53604, -116.119222",33.536040,-116.119222,Male,No,No,No,13,Yes,No,DSL,No,Yes,No,Yes,Yes,Yes,Month-to-month,No,Mailed check,73.35,931.55,No,0,65,4645,NaN
7031,9281-CEDRU,1,United States,California,Salton City,92275,"33.28156, -115.955541",33.281560,-115.955541,Female,No,Yes,No,68,Yes,No,DSL,No,Yes,No,Yes,Yes,No,Two year,No,Bank transfer (automatic),64.10,4326.25,No,0,48,5553,NaN
7032,2235-DWLJU,1,United States,California,Thousand Palms,92276,"33.849263, -116.382778",33.849263,-116.382778,Female,Yes,No,No,6,No,No phone service,DSL,No,No,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,44.40,263.05,No,0,71,4611,NaN
7033,0871-OPBXW,1,United States,California,Twentynine Palms,92277,"34.17211, -115.769773",34.172110,-115.769773,Female,No,No,No,2,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,20.05,39.25,No,0,80,5191,NaN
7034,3605-JISKB,1,United States,California,Twentynine Palms,92278,"34.457829, -116.139589",34.457829,-116.139589,Male,Yes,Yes,No,55,Yes,Yes,DSL,Yes,Yes,No,No,No,No,One year,No,Credit card (automatic),60.00,3316.1,No,0,71,4212,NaN
7035,9767-FFLEM,1,United States,California,Westmorland,92281,"33.03679, -115.60503",33.036790,-115.605030,Male,No,No,No,38,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Credit card (automatic),69.50,2625.25,No,0,35,4591,NaN
7036,8456-QDAVC,1,United States,California,Winterhaven,92283,"32.852947, -114.850784",32.852947,-114.850784,Male,No,No,No,19,Yes,No,Fiber optic,No,No,No,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),78.70,1495.1,No,0,20,2464,NaN
7037,7750-EYXWZ,1,United States,California,Yucca Valley,92284,"34.159534, -116.425984",34.159534,-116.425984,Female,No,No,No,12,No,No phone service,DSL,No,Yes,Yes,Yes,Yes,Yes,One year,No,Electronic check,60.65,743.3,No,0,24,3740,NaN
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,No,No,No,72,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No,0,45,5306,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,No,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,0,59,2140,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,No,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,71,5560,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,No,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,No,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,38,5097,NaN

In [70]:

pd.set_option('display.max_columns', None) 
df[ 'Churn Value'].value_counts()
df[ 'Churn Label'].value_counts()

Churn Label
nan    7043
Name: count, dtype: int64

In [53]:
print(df.columns.tolist())

['Count', 'Country', 'State', 'City', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value', 'TenureGroup', 'Churn']

In [9]:
df.describe(include='all')

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
count,7043,7043.0,7043,7043,7043,7043.000000,7043,7043.000000,7043.000000,7043,7043,7043,7043,7043.000000,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043.000000,7043,7043,7043.000000,7043.000000,7043.000000,1869
unique,7043,NaN,1,1,1129,NaN,1652,NaN,NaN,2,2,2,2,NaN,2,3,3,3,3,3,3,3,3,3,2,4,NaN,6531,2,NaN,NaN,NaN,20
top,3668-QPYBK,NaN,United States,California,Los Angeles,NaN,"34.02381, -118.156582",NaN,NaN,Male,No,No,No,NaN,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,,No,NaN,NaN,NaN,Attitude of support person
freq,1,NaN,7043,7043,305,NaN,5,NaN,NaN,3555,5901,3641,5416,NaN,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,NaN,11,5174,NaN,NaN,NaN,192
mean,NaN,1.0,NaN,NaN,NaN,93521.964646,NaN,36.282441,-119.798880,NaN,NaN,NaN,NaN,32.371149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,NaN,0.265370,58.699418,4400.295755,NaN
std,NaN,0.0,NaN,NaN,NaN,1865.794555,NaN,2.455723,2.157889,NaN,NaN,NaN,NaN,24.559481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,NaN,0.441561,21.525131,1183.057152,NaN
min,NaN,1.0,NaN,NaN,NaN,90001.000000,NaN,32.555828,-124.301372,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN,0.000000,5.000000,2003.000000,NaN
25%,NaN,1.0,NaN,NaN,NaN,92102.000000,NaN,34.030915,-121.815412,NaN,NaN,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,NaN,0.000000,40.000000,3469.000000,NaN
50%,NaN,1.0,NaN,NaN,NaN,93552.000000,NaN,36.391777,-119.730885,NaN,NaN,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,NaN,0.000000,61.000000,4527.000000,NaN
75%,NaN,1.0,NaN,NaN,NaN,95351.000000,NaN,38.224869,-118.043237,NaN,NaN,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,NaN,1.000000,75.000000,5380.500000,NaN
max,NaN,1.0,NaN,NaN,NaN,96161.000000,NaN,41.962127,-114.192901,NaN,NaN,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,NaN,1.000000,100.000000,6500.000000,NaN

In [10]:
for col in df.columns:
    print(f"{col} → {df[col].dtype} → NaN: {df[col].isna().sum()}")

CustomerID → object → NaN: 0
Count → int64 → NaN: 0
Country → object → NaN: 0
State → object → NaN: 0
City → object → NaN: 0
Zip Code → int64 → NaN: 0
Lat Long → object → NaN: 0
Latitude → float64 → NaN: 0
Longitude → float64 → NaN: 0
Gender → object → NaN: 0
Senior Citizen → object → NaN: 0
Partner → object → NaN: 0
Dependents → object → NaN: 0
Tenure Months → int64 → NaN: 0
Phone Service → object → NaN: 0
Multiple Lines → object → NaN: 0
Internet Service → object → NaN: 0
Online Security → object → NaN: 0
Online Backup → object → NaN: 0
Device Protection → object → NaN: 0
Tech Support → object → NaN: 0
Streaming TV → object → NaN: 0
Streaming Movies → object → NaN: 0
Contract → object → NaN: 0
Paperless Billing → object → NaN: 0
Payment Method → object → NaN: 0
Monthly Charges → float64 → NaN: 0
Total Charges → object → NaN: 0
Churn Label → object → NaN: 0
Churn Value → int64 → NaN: 0
Churn Score → int64 → NaN: 0
CLTV → int64 → NaN: 0
Churn Reason → object → NaN: 5174

In [55]:
df[ 'Total Charges']=pd.to_numeric(df[ 'Total Charges'],errors='coerce')
df[ 'Total Charges'].isna().sum

<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: Total Charges, Length: 7043, dtype: bool>

In [56]:
df[ 'Total Charges'].fillna(0,inplace=True)

In [63]:

df[ 'Churn'] = df[ 'Churn Label'].replace({'yes': 1, 'no': 0})

In [58]:
df.columns

Index(['Count', 'Country', 'State', 'City', 'Zip Code', 'Lat Long', 'Latitude',
       'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents',
       'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service',
       'Online Security', 'Online Backup', 'Device Protection', 'Tech Support',
       'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label',
       'Churn Value', 'TenureGroup', 'Churn'],
      dtype='object')

In [59]:
leakage_cols=[
    'CustomerID',
    'CLTV',
    'Churn Score',
    'Churn Reason'
]
df.drop(columns=[col for col in leakage_cols if col in df.columns], inplace=True)

In [60]:
def tenure_group(Tenure_Months):
    if Tenure_Months<=6:
        return '0-6 Months'
    elif Tenure_Months<=12:
        return '6-12 Months'
    elif Tenure_Months<=24:
        return '1-2 Years'
    else :
        return '2+ Years'
df['TenureGroup']=df['Tenure Months'].apply(tenure_group)

In [ ]:
df.head()
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Label,Churn Value
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,0.0,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,NaN,0.265370
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,NaN,0.441561
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,NaN,0.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,NaN,0.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,NaN,0.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,NaN,1.000000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,NaN,1.000000

In [64]:
df[ 'Churn'].value_counts()

Churn
nan    7043
Name: count, dtype: int64

In [67]:
df[	'Churn Label'].value_counts()

Churn Label
nan    7043
Name: count, dtype: int64

In [71]:
df.columns

Index(['Count', 'Country', 'State', 'City', 'Zip Code', 'Lat Long', 'Latitude',
       'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents',
       'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service',
       'Online Security', 'Online Backup', 'Device Protection', 'Tech Support',
       'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label',
       'Churn Value', 'TenureGroup', 'Churn'],
      dtype='object')

In [72]:
df[['Churn', 'Churn Label', 'Churn Value']].head()

  Churn Churn Label  Churn Value
0   nan         nan            1
1   nan         nan            1
2   nan         nan            1
3   nan         nan            1
4   nan         nan            1

In [75]:
df['Churn'] = df['Churn Value']
df[['Churn']].tail()

      Churn
7038      0
7039      0
7040      0
7041      0
7042      0

In [76]:
df.drop(columns=['Churn Label','Churn Value'], inplace=True)

In [77]:
df['Churn'].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [78]:
y=df['Churn']
x=df.drop(columns=['Churn'])

In [79]:
categorical_cols=x.select_dtypes(include='object').columns
categorical_cols

Index(['Country', 'State', 'City', 'Lat Long', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Phone Service', 'Multiple Lines',
       'Internet Service', 'Online Security', 'Online Backup',
       'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies',
       'Contract', 'Paperless Billing', 'Payment Method', 'TenureGroup'],
      dtype='object')

In [80]:
X_encoded = pd.get_dummies(
    x,
    columns=categorical_cols,
    drop_first=True
)